### ISSUE TITLE
Output shows "Unable to execute command: Internal error." after run "reboot" operation on TARGET machine via ssh method

### ISSUE THREAD

**Issue by XGWang0** [openSUSE/twopence#40]
After run command "twopence_command  -q $TARGET 'reboot'"  
Output displays "Unable to execute command: Internal error."

**Comment by Bischoff** [comment]
Hi,

This is normal: the "reboot" command never returns, so twopence does not receive any answer.

To do what you want to acheive, send "reboot &" background command, which returns.
