### ISSUE TITLE
fate: publish twopence.gem to rubygem.org

### ISSUE THREAD

**Issue by MalloZup** [openSUSE/twopence#53]
fate: publish twopence.gem to rubygem.org

**Comment by nodeg** [comment]
The gem has been published by @srbarrios but got removed early this year because of issues with it.

**Comment by srbarrios** [comment]
Yup. Basically I published a wrong gem as the gem must in fact be prepared as a native gem where each user built it for its system.
For now, we discard to work on this any time soon.
